config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]

    post :show, on: :member
  end

  resources :users, only: %i[ show edit update ]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    subscribers + [user]
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show]
  before_action :set_current_user_event, only: %i[edit update destroy]
  before_action :password_guard!, only: [:show]

  def index
    @events = Event.all
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode"]

    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end

      render 'password_form'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="card thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="card-body">
        <div class="event-description">
          <div class="card-title">
            <h3><%= link_to event.title, event_path(event) %></h3>
          </div>

          <div class="card-text">
            <h4><small><%= l event.datetime, format: :short %></small></h4>
            <div class="mt-2"><%= event.address %></div>
            <div>
              <% event.visitors.each do |user| %>
                <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: event} %>

  <div class="mt-2">
    <%= form.label :title, class: 'mb-1' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.label :address, class: 'mb-1' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.label :datetime, class: 'mb-1' %>
    <p><%= form.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="mt-2">
    <%= form.label :description, class: 'mb-1' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class='mt-2'>
    <%= form.label :pincode, class: 'mb-1' %>
    <%= form.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="mt-3">
    <%= form.submit t('buttons.save'), class: 'btn btn-primary' %>
    <%= link_to t('buttons.back'), :back, class: 'ms-2' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t('events.edit') %></h1>

<div class="row">
  <div class="col-6 mt-2">
    <%= render 'form', event: @event %>
  </div>

  <div class="my-2">
    <%= button_to t('buttons.delete_event'), event_path(@event), method: :delete,
                data: { confirm: t('delete_confirmation') },
                class: 'btn btn-danger' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= t('events.index') %></h1>

<div class="my-4">
  <%= link_to t('events.create'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row mb-2">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t('events.new') %></h1>

<div class="row">
  <div class="col-6 mt-2">
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1><%= t('events.need_pincode') %></h1>

<%= form_with(url: event_path, method: :post) do |form| %>
  <div class="mt-2">
    <%= form.label :pincode, t('pincode'), class: 'mb-1' %>
    <%= form.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions mt-3">
    <%= submit_tag t('buttons.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to t('buttons.to_root'), root_path %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{asset_path('event.jpg')})" %>

      <div class="event-info-inner row">
        <div class="col-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address,
                                   "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="my-2">
              <%= link_to t('events.edit'), edit_event_path(@event),
                          class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <div class="event-photos">
        <div class="event-photos-gallery row">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>
        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>
      
      <div class="event-comments my-2">
        <%= render partial: 'comments/form', locals: { comment: @new_comment || @event.comments.build } %>
        <div class="mt-2">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="event-owner">
        <h4><%= t('users.organized') %></h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4><%= t('users.will_go') %></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% unless current_user_can_edit?(@event) %>
        <div class="event-subscription-form">
          <h4><%= t('subscriptions.and_me') %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div id="map" data-address="<%= @event.address %>" style="width: 100%; height: 300px">
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'lightbox-event' %>
<%= javascript_pack_tag 'map' %>